version: '3'
services:
  #PHP Service
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ../taxi_driver/:/var/www/html
      - ./services/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ../taxi_driver/:/var/www/html
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
